
# Services
services:  
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
    image: mariadb:inception
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build:
      context: requirements/wordpress/
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - my_network
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    secrets:
      - credientials
      - db_password
    restart: always
    
  nginx:
    container_name: nginx
    image: nginx:inception
    build:
      context: requirements/nginx/
    ports:
      - "443:443"
    networks:
      - my_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    restart: always

  redis:
    container_name: redis
    image: redis:inception
    build: 
      context: requirements/bonus/redis/
    depends_on:
      - wordpress
    networks:
      - my_network
    volumes:
      - redis_volume:/data/
    restart: always

  adminer:
    container_name: adminer
    image: adminer:inception
    build: 
      context: requirements/bonus/adminer/
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - my_network

  static:
    container_name: static
    image: static:tamghart
    build: 
      context: requirements/bonus/static_website/
    ports:
      - "80:80"
    networks:
      - my_network
    restart: always


  ftp:
    container_name: ftp
    image: ftps:inception
    build: 
      context: requirements/bonus/ftp/
    networks:
      - my_network
    volumes:
      - wordpress_volume:/home/ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always

  portainer:
    container_name: portainer
    image: portainer:inception
    build: 
      context: requirements/bonus/extra/
    ports:
      - "9000:9000"
    networks:
      - my_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always


# Networks 
networks:
  my_network:
    name: my_network
    driver: bridge

# Volumes
volumes:
  mariadb_volume:
    name: mariadb_volume
    driver_opts:
      type: none
      device: /home/abounab/data/mariadb 
      o: bind
  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      type: none
      device: /home/abounab/data/wordpress
      o: bind
  redis_volume:
    name: redis_volume
    driver_opts:
      type: none
      device: /home/abounab/data/redis
      o: bind

# Secrets
secrets:
  credientials:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt