
services:  
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
    image: mariadb:inception
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build:
      context: requirements/wordpress/
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - my_network
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    
  nginx:
    container_name: nginx
    image: nginx:inception
    build:
      context: requirements/nginx/
    ports:
      - "443:443"
    networks:
      - my_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html/wordpress



networks:
  my_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver_opts:
      type: none
      device: /home/abounab/data/mariadb 
      o: bind
  wordpress_volume:
    driver_opts:
      type: none
      device: /home/abounab/data/wordpress
      o: bind
