
services:  
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
    image: mariadb:inception
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - mariadb_volume:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build:
      context: requirements/wordpress/
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - my_network
    volumes:
      - wordpress_volume:/var/www/html/wordpress
    secrets:
      - credientials
      - db_password
    
  nginx:
    container_name: nginx
    image: nginx:inception
    build:
      context: requirements/nginx/
    ports:
      - "443:443"
    networks:
      - my_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html/wordpress

  redis:
    container_name: redis
    image: redis:inception
    build: 
      context: requirements/bonus/redis/
    depends_on:
      - wordpress
    networks:
      - my_network
    volumes:
      - redis_volume:/data/
  
  # have to be configured
  adminer:
    container_name: adminer
    image: adminer
    build: 
      context: requirements/bonus/adminer/
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - my_network

  # have to be configured






networks:
  my_network:
    name: my_network
    driver: bridge

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver_opts:
      type: none
      device: /home/abounab/data/mariadb 
      o: bind
  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      type: none
      device: /home/abounab/data/wordpress
      o: bind
  redis_volume:
    name: redis_volume
    driver_opts:
      type: none
      device: /home/abounab/data/redis
      o: bind

secrets:
  credientials:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt