version: '3'

services:
  nginx:
    build:
      context: requirements/nginx/
    ports:
      - "443:443"
      # dockerfile: requirements/nginx/Dockerfile
    # volumes:
    #   - .requirements/tools:/etc/nginx/ssl/
    container_name: nginx
    networks:
      - my_network
  
  mariadb:
    build:
      context: requirements/mariadb/
    environment:
      - DB_NAME=${MYSQL_NAME}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASS}
      - DB_ROOT=${MYSQL_ROOT}
    ports:
      - "3306:3306"
    container_name: mariadb
    networks:
      - my_network
    volumes:
      - mariadb_volume:/var/lib/mysql



networks:
  my_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver_opts:
      type: none
      device: /home/abounab/data/mariadb 
      o: bind
  wordpress_volume:
    driver_opts:
      type: none
      device: /home/abounab/data/wordpress
      o: bind
    