version: '3'

services:
  nginx:
    build:
      context: requirements/nginx/
    ports:
      - "443:443"
      # dockerfile: requirements/nginx/Dockerfile
    # volumes:
    #   - .requirements/tools:/etc/nginx/ssl/
    container_name: nginx
    
    