version: '3'

services:  
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress/
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - my_network
    volumes:
      - wordpress_volume:/var/www/html
    
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
    ports:
      - "443:443"
    networks:
      - my_network
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html



networks:
  my_network:
    driver: bridge

volumes:
  mariadb_volume:
    driver_opts:
      type: none
      device: /home/abounab/data/mariadb 
      o: bind
  wordpress_volume:
    driver_opts:
      type: none
      device: /home/abounab/data/wordpress
      o: bind
